services:
  apache-httpd:
    container_name: httpd-server
    build:
      context: ./httpd/
      args:
         - APACHE_LOG_DIR="/var/log/httpd-server/"
    restart: on-failure
    ports:
      - "8080:80"