services:
#  apache-httpd:
#    container_name: httpd-server-apache
#    build:
#      context: ./httpd/
#      dockerfile: ./Dockerfile-apache
#      args:
#         - APACHE_LOG_DIR="/var/log/httpd-server/"
#    restart: on-failure
#    ports:
#      - "8080:80"
#    networks:
#      - internal_net

  nginx-httpd:
    container_name: httpd-server-nginx
    build:
      context: ./httpd/
      dockerfile: ./Dockerfile-nginx
    restart: on-failure
    ports:
      - "8080:80"
    networks:
      - internal_net
      
  java-fastcgi:
    container_name: fastcgi-server
    build:
      context: ./server/
    restart: on-failure
    depends_on:
    #  - apache-httpd
      - nginx-httpd
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge